### PR TITLE
Hot fix 1.3.4 in master (v2)

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
Error:

```
=== Searching for apps in the repo ===
    Found 1 app in this repo : 
      Framework Hotline
        Xcode Project : Hotline.xcodeproj
        Target : Hotline
        Scheme : Hotline - Debug, with build configuration Debug (Generated by buddybuild)
        Scheme : Hotline - Release, with build configuration Release (Generated by buddybuild)
    Buddybuild could not find the selected scheme: 'HotlineIO' in the list of schemes found for your specified application: [Hotline - Debug,Hotline - Release].
    The selected scheme has likely been removed or renamed. Please go to your build settings and switch to another scheme.
```

**Comment by rudolf-adamkovic** [comment]
Related: #27

**Review by nasakinmaxim — APPROVED** [review]
LGTM.

**Comment by rudolf-adamkovic** [comment]
Tagged.

**Pull request merged**
