### PR TITLE
Convert static library to framework

### LINKED ISSUE #1: Convert static library to dynamic framework

### PR DESCRIPTION
**Pull request by nasakinmaxim**
Close #1.

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
Waiting for #4.

**Comment by rudolf-adamkovic** [comment]
In review.

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]
@nasakinmaxim

Well, all of our projects have Deployment Target set to 9.0 whereas you set it to 9.3. That will cause an error when integrating into our app.

Also, the HotlineIO doesn't need to override the default Deployment Target, neither other things. Be sure to configure everything you can on project level, not target level.

**Comment by rudolf-adamkovic** [comment]
Waiting for #4.

**Comment by nasakinmaxim** [comment]
@salutis 
>Waiting for #4.

It's done. Could you please review the PR?

**Comment by rudolf-adamkovic** [comment]
In review.

**Review by rudolf-adamkovic — APPROVED** [review]

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Nice!

**Pull request merged**
